---
# handlers/main.yml

- name: enable wordpress site
  become: yes
  command: a2ensite wordpress.conf
  args:
    # ne ré-active le site que s'il n'est pas déjà dans sites-enabled
    creates: /etc/apache2/sites-enabled/wordpress.conf
  notify: restart apache

- name: restart apache
  become: yes
  command: /etc/init.d/apache2 restart

- name: restart httpd
  become: yes
  command: /etc/init.d/httpd restart
